new TStruct("PaymentCacheableSettings");
new TField("timestamps", (byte) 13, 1);
new TField("menus", (byte) 13, 2);
new TField("urls", (byte) 13, 3);
new TField("urlGroups", (byte) 13, 4);
new TField("tosUrlBundles", (byte) 13, 5);
new TField("cardValidationRules", (byte) 15, 6);
new TField("messages", (byte) 13, 7);
new TField("myCode", (byte) 12, 8);
new TField("invoice", (byte) 12, 9);
new TField("features", (byte) 13, 10);
new FieldMetaData("timestamps", DEFAULT, new MapMetaData((byte) 13, new EnumMetaData((byte) 16, g.a.b.e0.a.d.rc.class), new FieldValueMetaData((byte) 10, "Timestamp"))));
new FieldMetaData("menus", DEFAULT, new MapMetaData((byte) 13, new EnumMetaData((byte) 16, g.a.b.e0.a.d.o1.class), new ListMetaData((byte) 15, new StructMetaData((byte) 12, g.a.b.e0.a.d.PaymentCountrySettingMenu.class)))));
new FieldMetaData("urls", DEFAULT, new MapMetaData((byte) 13, new FieldValueMetaData((byte) 11, "PaymentUrlId"), new StructMetaData((byte) 12, g.a.b.e0.a.d.PaymentUrlInfo.class))));
new FieldMetaData("urlGroups", DEFAULT, new MapMetaData((byte) 13, new EnumMetaData((byte) 16, g.a.b.e0.a.d.gd.class), new ListMetaData((byte) 15, new FieldValueMetaData((byte) 11, "PaymentUrlId")))));
new FieldMetaData("tosUrlBundles", DEFAULT, new MapMetaData((byte) 13, new EnumMetaData((byte) 16, g.a.b.e0.a.d.wc.class), new ListMetaData((byte) 15, new StructMetaData((byte) 12, g.a.b.e0.a.d.PaymentTosUrlBundle.class)))));
new FieldMetaData("cardValidationRules", DEFAULT, new ListMetaData((byte) 15, new StructMetaData((byte) 12, g.a.b.e0.a.d.PaymentCardValidationRule.class))));
new FieldMetaData("messages", DEFAULT, new MapMetaData((byte) 13, new EnumMetaData((byte) 16, g.a.b.e0.a.d.m1.class), new MapMetaData((byte) 13, new FieldValueMetaData((byte) 11), new FieldValueMetaData((byte) 11)))));
new FieldMetaData("myCode", DEFAULT, new StructMetaData((byte) 12, g.a.b.e0.a.d.PaymentMyCode.class)));
new FieldMetaData("invoice", DEFAULT, new StructMetaData((byte) 12, g.a.b.e0.a.d.PayInvoiceSetting.class)));
new FieldMetaData("features", DEFAULT, new MapMetaData((byte) 13, new EnumMetaData((byte) 16, g.a.b.e0.a.d.t.class), new MapMetaData((byte) 13, new FieldValueMetaData((byte) 11), new FieldValueMetaData((byte) 11)))));
